speech_text = """My Dear Compatriots, I stand in humble gratitude to you, this day, having just sworn to the oath of office as President, Commander-In-Chief of the Armed Forces of our great nation. 
I thank you all, fellow citizens, for the trust and confidence, which you have demonstrated through the power of your vote. I want to assure you, that I will do my utmost at all times, to continue to deserve your trust. 
I would like to specially acknowledge the presence in our midst today, of Brother Heads of State and Government, who have come to share this joyous moment with us. Your Excellencies, I thank you for your solidarity. I also wish to express my gratitude, to the Representatives of Heads of State and Government who are here with us. My appreciation also goes to the chairperson of the African Union and other world leaders, our development partners, and all our distinguished guests. 
I want to specially thank all Nigerians for staying the course in our collective commitment to build a democratic nation. To members of the PDP family and members of other political parties, who have demonstrated faith in our democratic enterprise, I salute you. 
At this juncture, let me acknowledge and salute my friend and brother, Vice-President Namadi Sambo, and my dear wife, Patience, who has been a strong pillar of support. 
I thank her for galvanizing and mobilizing Nigeria women for the cause of democracy. In the same vein, I owe a

debt of gratitude to my mother and later father. I cannot thank them enough. 
I cannot but pay tribute to our late President, Alhaji Umaru Musa Yar'Adua with whom we won the Presidential election four years ago, when I contested as his running mate. May God bless his soul. 
I also wish to pay tribute our founding fathers, whose enduring sacrifices and abiding faith in the unity and greatness of our country. Laid the foundation for the nation. We take enormous pride in their contributions. The pivotal task of this generation is to lift our fatherland to the summit of greatness. 
Your Excellencies, Distinguished Ladies and Gentlemen, earlier this year, over seventy-three million eligible Nigerians endures all manner of inconvenience just to secure their voters cards, in order to exercise the right to choose those that will govern them. 
At the polls, we saw the most dramatic expressions of the hunger for democracy. Stories of courage and patriotism were repeated in many ways, including how fellow citizens helped physically challenged voters into polling stations to enable them exercise their franchise. The inspiring story of the one hundred and three year-old man, and many like him across the country, who struggled against the physical limitations of age to cast their vote, is noteworthy. 
Such determination derives from the typical Nigerian spirit of resilience in the face of the greatest of odds. That spirit has, over the years, stirred our hopes, doused our fears, and encouraged us to gather ourselves to build a strong nation even when others doubted our capacity. 
Today, our unity is firm, and our purpose is strong. Our determination unshakable. Together, we will unite our nation and improve the living standards of all our peoples whether in the North or in the South; in the East or in the West. Our decade of development has begun. The march is on. The day of transformation begins today. We will not allow anyone exploit differences in creed or tongue, to set us one against another. Let me at this point congratulate the elected Governors, Senators, members of the House of Representatives and those of the State s Houses of Assembly for their victories at the polls. 
I am mindful that I represent the shared aspiration of all our people to forge a united Nigeria: a land of justice, opportunity and plenty, Confident that a people that are truly committed to a noble ideal, cannot be denied the realization of their vision. I assure you that this dream of Nigeria that is so deeply felt by millions will indeed come to reality. 
A decade ago, it would have been a mere daydream to think that a citizen from a minority ethnic group could galvanize national support, on an unprecedented scale, to discard ancient prejudices, and win the people's mandate as President of our beloved country. That result emanated from the toil and sacrifice of innumerable individuals and institutions, many of whom may never get to receive public appreciation for their effort. 
Only a couple of days ago, I received an entry on my Facebook page. It will sent by Mr. Babajide Orevba. He wrote to inform me that I had lost a great fan. That fan was his father, Mr. Emmanuel Bamidele Orevba. The deceased, the son told me, was no politician, but has campaigned enthusiastically for my ticket. Tragically, overwhelmed by the joy of our victory, he collapsed, and passed on three days later. I pray God Almighty to grant his soul eternal rest. 
The success of the 2011 elections and the widespread acclaim which the exercise received was due to the uncommon patriotism and diligence exhibited by many Nigerians, including members of the Armed Forces, National Youth Service Corps (NYSC) and others. Unfortunately, despite the free, fair and transparent manner the elections were conducted, a senseless wave of violence in some parts of the country led to the death of ten members of the NYSC and others. These brave men and women paid the supreme sacrifice in the service of our fatherland. They are heroes of our democracy. We offer our heartfelt prayers and condolences in respect of all those who lost their lives. 
In the days ahead, those of us that you have elected to serve must show that we are men and women with the patriotism and passion, to match the hopes and aspirations of you, the greater people of this country. We must demonstrate the leadership, statesmanship, vision, capacity, and sacrifice, to transform our nation. We must strengthen common grounds, develop new areas of understanding and collaboration, and seek fresh ideas that will enrich our national consensus. 
It is the supreme task of this generation to give hope to the hopeless, strength to the weak and protection to the defenceless. 
Fellow citizens, the leadership we have pledged is decidedly transformative. The transformation will be achieved in all the critical sectors, by harnessing the creative energies of our people. 
We must grow the economy, create jobs, and generate enduring happiness for our people. I have great confidence in the ability of Nigerians to transform this country. The urgent task of my administration is to provide a suitable environment, for productive activities to flourish. I therefore call on the good people of Nigeria, to enlist as agents of this great transformation. 
My dear countrymen and women, being a Nigerian is a blessing. It is also a great responsibility. We must make a vow that, together, we will make the Nigerian Enterprise thrive. 
The leadership and the followership must strive to convert our vast human and natural resources into the force that leads to a great Nigeria. The Nigeria of our dreams must be built on handwork and not on short cuts. Let me salute the Nigerian workers who build our communities, cities and country. They deserve fair rewards, and so do the women that raise our children, and the rural dwellers that grow our food.

The moment is right. The signs are heart-warning. We are ready to take off on the path of sustained growth and economic development. In our economic strategy, there will be appropriate policy support to the real sector of the economy, so that Small and Medium Enterprises may thrive. Nigeria is blessed with enormous natural wealth, and my Administration will continue to encourage locally owned rapidly expanding population. But this must be a collaborative effort.

We must form technical land financial partnerships with global businesses and organizations. We live in an age where no country can survive on its own; countries depend on each other for economic well-being. Nigeria is no different. Returns on investment in Nigeria remain among the highest in the world. We will continue to welcome sustainable investment in our economy.

We will push programs and policies that will benefit both local and foreign businesses, but we must emphasize mutual benefits and win-win relationships. The overall ongoing reforms in the banking and financial sectors are therefore designed to support the real sector of the economy. 
To drive our overall economic vision, the power sector reform is at the heart of our industrialization strategy. I call on all stakeholders, to co-operate with my administration, to ensure the success of the reforms.

Over the next four years, attention will be focused on rebuilding our infrastructure. We will create greater access to quality education and improved health care delivery, we will pay special attention to the agricultural sector, to enable it play its role of ensuring food security and massive job creation for our people.

The creation of the Nigerian Sovereign Investment Authority will immensely contribute to strengthening our fiscal framework, by institutionalizing savings of our commodity-related revenues. With this mechanism in place, we will avoid the boom and bust cycles, and mitigate our exposure to oil price volatility. 
The lesson we have learnt is that the resolution of the Niger Delta issue is crucial for the health of the nation'
Fellow citizens, in every decision, I shall always place the common good before all else. The bane of corruption shall be met by the overwhelming force of our collective determination, to rid our nation of this scourge. The fight against corruption is a war in which we must all enlist, so that the limited resources of this nation will be used for the growth of our common wealth.

I am confident that we have every reason to look to the future with hope. We owe ourselves and posterity the duly of making this country respectable in the comity of nations. Nigeria, as a responsible member of the international community, will remain committed to the maintenance of global peace and security. We will continue to play an active role in the United Nations. Our role in the African Union, ECOWAS, and the Gulf of Guinea will be enhanced to ensure greater human and energy security. 
Your Excellencies, Distinguished Ladies and Gentlemen, this is a new dawn for Africa. We fought for decolonization. We will now fight for democratization. Nigeria, in partnership with the African Union, will lead the process for democracy and development in Africa in particular. We will support the consolidation of democracy, good governance and human rights in the continent. Africa must develop its vast resources to tackle poverty and under development. 
Conscious of the negative effect of insecurity on growth and development, my administration will seek collaboration at bilateral and multilateral levels, to improve our capability in combating trans-border crimes. In this regard, we will intensify our advocacy against the illicit trade in small arms and light weapons, which have become the catalyst for conflicts on the African continent. All Nigerian diplomatic missions abroad are to accord this vision of defending the dignity of humanity the highest priority. 
My fellow countrymen and women, Nigerian is not just a land of promise; it shall be a nation where positive change will continue to take place, for the good of our people. The time for lamentation is over. This is the era of transformation. This is the time for action. But Nigerian can only be transformed if we all play our parts with commitment and sincerity. Cynicism and skepticism will not help our journey to greatness. Let us all believe in a new Nigerian. Let us work together to build a great country that we will all be proud of. This is our hour. 
Fellow Compatriots, lift your gaze towards the horizon. Look ahead and you will see a great future that we can

secure with unity, hard work and collective sacrifice. 
Join me now as begin the journey of transforming Nigeria
*	I will continue to fight, for your future, because I am one of you.
*	I will continue to fight, for improved medical care for all our citizens 
*	I will continue to fight for all citizens to have access to first class education
*	I will continue to fight, for electricity to be available to all our citizens 
*	I will continue to fight, for an efficient and affordable public transport system for all our people
*	I will continue to fight for jobs to be created through productive partnerships.
You have trusted me with your mandate, and I will never, never let you down. 
I know your pain, because I have been there. Look beyond the hardship you have endured. See a new beginning, a new direction; a new spirit.

Nigerians, I want you to start to dream again. What you see in your dreams, we can achieve together. I call upon all the Presidential candidates who contested with me to join hands with us as we begin the transformation of our country.

Let us work together, let us build together, let us bequeath a greater Nigeria to the generations to come. 
I thank you! God bless you all! And God bless the Federal Republic of Nigeria."""