#PYTHON OPERATORS
# + ---> ADDITION
# - ---> SUBTRACTION
# / ---> DIVISION
# * ---> MULTIPLICATION
# % ---> MODULUS
# ** ---> EXPONENT


X = 5%3 #modulus RETURNS 2 REMAINDER AFTER DIVISION
print(X)

X = 5/3 #NORMAL DIVISION RETURNS A FLOAT WITH DECIMAL VALUES
print("NORMAL DIVISION :", X)

X = 5//3 #FLOOR DIVISION RETURNS A INTEGER ROUNDED DOWN
print("FLOOR DIVISION :", X)

X = 5 ** 3 #EXPONENT RAISES TO POWER
print("EXPONENT OPERATION :", X)

#ASSIGNMENT OPERATORS     
# = ---> BASIC ASSIGNMENT
# += ---> ADDITION & ASSIGN
# -= ---> SUBTRACTION & ASSIGN
# *= ---> MULTIPLICATION & ASSIGN

print("\nAT BASIC ASSIGNMENT\n")
APPLES = 6 # BASIC ASSIGNMENT, ASSIGN VARIABLES
print("APPLES : ", APPLES)

print("AT subtract and ASSIGNMENT\n\n".upper())
    
APPLES -= 1 # SUBTRACTION & ASSIGN VARIABLES
print("APPLES : ", APPLES)
APPLES -= 1 # SUBTRACTION & ASSIGN VARIABLES
print("APPLES : ", APPLES)
APPLES -= 1 # SUBTRACTION & ASSIGN VARIABLES
print("APPLES : ", APPLES)
APPLES -= 1 # SUBTRACTION & ASSIGN VARIABLES
print("APPLES : ", APPLES)
APPLES -= 1 # SUBTRACTION & ASSIGN VARIABLES
print("APPLES : ", APPLES)
APPLES -= 1 # SUBTRACTION & ASSIGN VARIABLES
print("APPLES : ", APPLES)


print("\n\nAT add and ASSIGNMENT\n\n".upper())

APPLES += 1 # ADD & ASSIGN VARIABLES
print("APPLES : ", APPLES)
APPLES += 1 # ADD & ASSIGN VARIABLES
print("APPLES : ", APPLES)
APPLES += 1 # ADD & ASSIGN VARIABLES
print("APPLES : ", APPLES)
APPLES += 1 # ADD & ASSIGN VARIABLES
print("APPLES : ", APPLES)
APPLES += 1 # ADD & ASSIGN VARIABLES
print("APPLES : ", APPLES)
APPLES += 1 # ADD & ASSIGN VARIABLES
print("APPLES : ", APPLES)

print("\n\nAT multiply and ASSIGNMENT\n\n".upper())

APPLES *= 2 # MULTIPLY  & ASSIGN VARIABLES
print("APPLES : ", APPLES)
APPLES *= 2 # MULTIPLY  & ASSIGN VARIABLES
print("APPLES : ", APPLES)
APPLES *= 2 # MULTIPLY  & ASSIGN VARIABLES
print("APPLES : ", APPLES)
APPLES *= 2 # MULTIPLY  & ASSIGN VARIABLES
print("APPLES : ", APPLES)
APPLES *= 2 # MULTIPLY  & ASSIGN VARIABLES
print("APPLES : ", APPLES)
APPLES *= 2 # MULTIPLY  & ASSIGN VARIABLES
print("APPLES : ", APPLES)
